# Generated by Django 3.2.8 on 2021-10-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50, verbose_name='Название книги')),
                ('article_text', models.TextField(verbose_name='описание книги')),
            ],
        ),
    ]
