# Generated by Django 3.2.8 on 2021-10-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50, verbose_name='Название книги')),
                ('article_author', models.CharField(max_length=30, verbose_name='автор')),
                ('article_text', models.TextField(verbose_name='описание книги')),
                ('date', models.CharField(max_length=10, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
