# Generated by Django 3.2.8 on 2021-10-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles11_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles11',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Дата выхода'),
        ),
    ]
